# Generated by Django 5.2.5 on 2025-09-13 15:29

import Employee_Tracker.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_activity_type', models.CharField(choices=[('Day_Shift', 'Day_Shift'), ('Late', 'Late_Shift'), ('Recon_Shift', 'Recon_Shift'), ('Night_Shift', 'Night_Shift')], default='Night_Shift', max_length=50)),
                ('report_type', models.CharField(choices=[('End_of_Shift', 'End_of_Shift'), ('Emergency', 'Emergency'), ('Break', 'Break'), ('Other', 'Other')], default='other', max_length=50)),
                ('activity_description', models.TextField()),
                ('tickets_resolved', models.IntegerField(default=0)),
                ('calls_made', models.IntegerField(default=0)),
                ('issues_escalated', models.IntegerField(default=0)),
                ('notes', models.TextField()),
                ('activity_submitted_at', models.DateTimeField()),
                ('is_approved', models.BooleanField(default=False)),
                ('activity_approved_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'Activity Report',
                'verbose_name_plural': 'Activity Reports',
                'ordering': ['report_type', 'shift_activity_type'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_date', models.DateField()),
                ('shift_start_time', models.TimeField()),
                ('shift_end_time', models.TimeField()),
                ('shift_updated_at', models.DateTimeField(auto_now=True)),
                ('shift_type', models.CharField(choices=[('Day_Shift', 'Day_Shift'), ('Late', 'Late_Shift'), ('Recon_Shift', 'Recon_Shift'), ('Night_Shift', 'Night_Shift')], default='Day_Shift', max_length=50)),
                ('shift_status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Active', 'Active'), ('Completed', 'Completed'), ('Missed', 'Missed'), ('Scheduled', 'Scheduled')], default='Scheduled', max_length=50)),
            ],
            options={
                'verbose_name': 'Shift',
                'verbose_name_plural': 'Shifts',
                'ordering': ['shift_agent', 'shift_date'],
            },
        ),
        migrations.CreateModel(
            name='WebHook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_name', models.CharField(max_length=100)),
                ('webhook_url', models.URLField(unique=True)),
                ('webhook_event_types', models.JSONField(default=Employee_Tracker.models.event)),
                ('secret_key', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'WebHooks',
            },
        ),
        migrations.CreateModel(
            name='WebHookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_types', models.JSONField(default=Employee_Tracker.models.event)),
                ('response_status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Active', 'Active'), ('Completed', 'Completed'), ('Missed', 'Missed'), ('Scheduled', 'Scheduled')], default='Scheduled', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('response_body', models.JSONField()),
            ],
            options={
                'verbose_name_plural': 'WebHook Logs',
            },
        ),
    ]
