# Generated by Django 5.2.5 on 2026-02-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_activity_type', models.CharField(choices=[('Day_Shift', 'Day_Shift'), ('Late_Shift', 'Late_Shift'), ('Recon_Shift', 'RS_Shift'), ('Night_Shift', 'Night_shift')], default='Night_Shift', max_length=50)),
                ('report_type', models.CharField(choices=[('End_of_Shift', 'End_of_Shift'), ('Emergency', 'Emergency'), ('Break', 'Break'), ('Other', 'Other')], default='other', max_length=50)),
                ('activity_description', models.TextField()),
                ('tickets_resolved', models.IntegerField(default=0)),
                ('calls_made', models.IntegerField(default=0)),
                ('issues_escalated', models.IntegerField(default=0)),
                ('notes', models.TextField()),
                ('activity_submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('activity_approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['report_type', 'activity_submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_in_time', models.DateTimeField()),
                ('clock_out_time', models.DateTimeField(blank=True, null=True)),
                ('duration_hours', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('clocked_in', 'Clocked_In'), ('clocked_out', 'Clocked_Out'), ('on_break', 'Break')], default='clocked_in', max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
                'ordering': ['-clock_in_time'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_date', models.DateField()),
                ('shift_start_time', models.TimeField()),
                ('shift_end_time', models.TimeField()),
                ('shift_type', models.CharField(choices=[('Day_Shift', 'Day_Shift'), ('Late_Shift', 'Late_Shift'), ('Recon_Shift', 'RS_Shift'), ('Night_Shift', 'Night_shift')], default='Day_Shift', max_length=50)),
                ('shift_status', models.CharField(choices=[('shift_completed', 'Shift_Completed'), ('shift_in_progress', 'Shift_In_Progress'), ('shift_scheduled', 'Shift_Scheduled'), ('shift_cancelled', 'Shift_Cancelled'), ('shift_missed', 'Shift_Missed'), ('no_show', 'No_Show')], default='no_show', max_length=50)),
                ('shift_created_at', models.DateTimeField(auto_now_add=True)),
                ('shift_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shift',
                'verbose_name_plural': 'Shifts',
                'ordering': ['-shift_date', 'shift_start_time'],
            },
        ),
    ]
