# Generated by Django 5.2.5 on 2026-01-31 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Tracker', '0001_initial'),
        ('accounts', '0004_alter_customuser_email_alter_employee_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.employee'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='shift_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='accounts.employee'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='shift_status',
            field=models.CharField(choices=[('shift_completed', 'Shift_Completed'), ('shift_in_progress', 'Shift_In_Progress'), ('shift_scheduled', 'Shift_Scheduled'), ('shift_cancelled', 'Shift_Cancelled'), ('shift_missed', 'Shift_Missed'), ('no_show', 'No_Show')], default='no_show', max_length=50),
        ),
    ]
