# Generated by Django 5.2.5 on 2025-08-26 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='employee',
            new_name='shift_agent',
        ),
        migrations.RenameField(
            model_name='shift',
            old_name='date',
            new_name='shift_date',
        ),
        migrations.RenameField(
            model_name='shift',
            old_name='end_time',
            new_name='shift_end_time',
        ),
        migrations.RenameField(
            model_name='shift',
            old_name='start_time',
            new_name='shift_start_time',
        ),
        migrations.RenameField(
            model_name='shift',
            old_name='updated_at',
            new_name='shift_updated_at',
        ),
    ]
