# Generated by Django 5.2.5 on 2025-11-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Tracker', '0001_initial'),
        ('accounts', '0003_alter_employee_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityreport',
            name='shift_activity_type',
            field=models.CharField(choices=[('Day_Shift', 'Day_Shift'), ('Late', 'Late_Shift'), ('Recon_Shift', 'RS_Shift'), ('Night_Shift', 'Night_shift'), ('Scheduled', 'Scheduled')], default='Night_Shift', max_length=50),
        ),
        migrations.AlterField(
            model_name='shift',
            name='shift_status',
            field=models.CharField(choices=[('Shift_Started', 'Shift_Started'), ('Shift_Completed', 'Shift_Completed'), ('Scheduled', 'Scheduled')], default='Signed_In', max_length=50),
        ),
        migrations.AlterField(
            model_name='shift',
            name='shift_type',
            field=models.CharField(choices=[('Day_Shift', 'Day_Shift'), ('Late', 'Late_Shift'), ('Recon_Shift', 'RS_Shift'), ('Night_Shift', 'Night_shift'), ('Scheduled', 'Scheduled')], default='Day_Shift', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='activityreport',
            unique_together={('report_type', 'shift_active_agent')},
        ),
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together={('shift_agent', 'shift_date')},
        ),
    ]
