# Generated by Django 5.2.5 on 2026-01-29 12:08
import django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='shift',
            field=models.ForeignKey(
                to='Employee_Tracker.Shift',
                on_delete=django.db.models.deletion.SET_NULL,
                null=True,
                blank=True,
                related_name='shift_attendance',
            ),
        )

    ]
