# Generated by Django 5.2.5 on 2026-06-22 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='static_shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shift_instances', to='Employee_Tracker.staticshift'),
        ),
    ]
