# Generated by Django 5.2.5 on 2025-09-11 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Employee_Tracker', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityreport',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='shift',
            name='shift_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='activityreport',
            name='shift_active_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_active_agent', to='Employee_Tracker.shift'),
        ),
        migrations.AddField(
            model_name='webhook',
            name='webhook_created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='webhooklog',
            name='webhook_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee_Tracker.webhook'),
        ),
        migrations.AlterUniqueTogether(
            name='webhook',
            unique_together={('webhook_name', 'webhook_url')},
        ),
        migrations.AlterUniqueTogether(
            name='webhooklog',
            unique_together={('webhook_config', 'event_types')},
        ),
    ]
