# Generated by Django 5.2.5 on 2025-09-13 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityreport',
            name='activity_title',
        ),
    ]
