# Generated by Django 5.2.5 on 2026-06-23 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Tracker', '0002_shift_static_shift'),
        ('accounts', '0005_alter_employee_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='validation_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='validation_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='shift_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to='accounts.employee'),
        ),
    ]
