# Generated by Django 5.2.5 on 2025-12-28 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Tracker', '0002_alter_activityreport_shift_activity_type_and_more'),
        ('accounts', '0004_alter_customuser_email_alter_employee_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityreport',
            name='shift_activity_type',
            field=models.CharField(choices=[('Day_Shift', 'Day_Shift'), ('Late_Shift', 'Late_Shift'), ('Recon_Shift', 'RS_Shift'), ('Night_Shift', 'Night_shift')], default='Night_Shift', max_length=50),
        ),
        migrations.AlterField(
            model_name='shift',
            name='shift_status',
            field=models.CharField(choices=[('Shift_Started', 'Shift_Started'), ('Shift_Completed', 'Shift_Completed'), ('In_Progress', 'In_Progress')], default='Signed_In', max_length=50),
        ),
        migrations.AlterField(
            model_name='shift',
            name='shift_type',
            field=models.CharField(choices=[('Day_Shift', 'Day_Shift'), ('Late_Shift', 'Late_Shift'), ('Recon_Shift', 'RS_Shift'), ('Night_Shift', 'Night_shift')], default='Day_Shift', max_length=50),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_in_time', models.DateTimeField()),
                ('clock_out_time', models.DateTimeField(blank=True, null=True)),
                ('duration_hours', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.employee')),
            ],
            options={
                'ordering': ['-clock_in_time'],
            },
        ),
    ]
