# Generated by Django 5.2.5 on 2025-09-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Tracker', '0002_remove_activityreport_activity_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityreport',
            name='activity_approved_at',
        ),
        migrations.AlterField(
            model_name='activityreport',
            name='activity_submitted_at',
            field=models.DateTimeField(),
        ),
    ]
