# Generated by Django 5.2.5 on 2026-03-31 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Tracker', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='shift',
            new_name='shift_attendance_type',
        ),
    ]
