# Generated by Django 5.2.5 on 2025-08-26 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Tracker', '0002_rename_employee_shift_shift_agent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activityreport',
            old_name='approved_at',
            new_name='activity_approved_at',
        ),
        migrations.RenameField(
            model_name='activityreport',
            old_name='description',
            new_name='activity_description',
        ),
        migrations.RenameField(
            model_name='activityreport',
            old_name='submitted_at',
            new_name='activity_submitted_at',
        ),
        migrations.RenameField(
            model_name='activityreport',
            old_name='title',
            new_name='activity_title',
        ),
    ]
