# Generated by Django 5.2.5 on 2026-06-23 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Tracker', '0003_attendance_validation_error_and_more'),
        ('accounts', '0005_alter_employee_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityreport',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reports', to='accounts.employee'),
        ),
        migrations.CreateModel(
            name='ShiftArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_date', models.DateField()),
                ('shift_status', models.CharField(choices=[('shift_completed', 'Shift_Completed'), ('shift_in_progress', 'Shift_In_Progress'), ('shift_scheduled', 'Shift_Scheduled'), ('no_show', 'No_Show')], max_length=50)),
                ('shift_created_at', models.DateTimeField()),
                ('shift_updated_at', models.DateTimeField()),
                ('original_shift_id', models.IntegerField()),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.employee')),
                ('shift_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achived_shifts', to='accounts.employee')),
                ('static_shift', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Employee_Tracker.staticshift')),
            ],
            options={
                'verbose_name': 'Archived Shift',
                'verbose_name_plural': 'Archived Shifts',
                'ordering': ['-archived_at'],
            },
        ),
    ]
