# Generated by Django 5.2.5 on 2025-08-26 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Tracker', '0003_rename_approved_at_activityreport_activity_approved_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activityreport',
            old_name='employee_emp',
            new_name='supervisor',
        ),
    ]
