# Generated by Django 5.2.5 on 2026-03-31 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Tracker', '0003_rename_shift_attendance_shift_attendance_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='shift_attendance_type',
            new_name='shift_attendance',
        ),
    ]
