# Generated by Django 5.2.5 on 2025-08-26 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Tracker', '0004_rename_employee_emp_activityreport_supervisor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activityreport',
            old_name='shift',
            new_name='shift_active_agent',
        ),
    ]
