# Generated by Django 5.2.5 on 2025-08-26 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Tracker', '0005_rename_shift_activityreport_shift_active_agent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webhook',
            old_name='created_by',
            new_name='webhook_created_by',
        ),
        migrations.RenameField(
            model_name='webhook',
            old_name='event_types',
            new_name='webhook_event_types',
        ),
        migrations.RenameField(
            model_name='webhook',
            old_name='name',
            new_name='webhook_name',
        ),
        migrations.RenameField(
            model_name='webhook',
            old_name='web_url',
            new_name='webhook_url',
        ),
        migrations.RenameField(
            model_name='webhooklog',
            old_name='web_hook_config',
            new_name='webhook_config',
        ),
        migrations.AlterField(
            model_name='activityreport',
            name='shift_active_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_active_agent', to='Employee_Tracker.shift'),
        ),
    ]
