# Generated by Django 5.2.5 on 2025-08-26 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Tracker', '0006_rename_created_by_webhook_webhook_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityreport',
            options={'verbose_name': 'Activity Report', 'verbose_name_plural': 'Activity Reports'},
        ),
        migrations.AlterModelOptions(
            name='shift',
            options={'verbose_name': 'Shift', 'verbose_name_plural': 'Shifts'},
        ),
        migrations.AlterModelOptions(
            name='webhook',
            options={'verbose_name_plural': 'WebHooks'},
        ),
        migrations.AlterModelOptions(
            name='webhooklog',
            options={'verbose_name_plural': 'WebHook Logs'},
        ),
        migrations.AlterUniqueTogether(
            name='webhook',
            unique_together={('webhook_name', 'webhook_url')},
        ),
        migrations.AlterUniqueTogether(
            name='webhooklog',
            unique_together={('webhook_config', 'event_types')},
        ),
    ]
