# Generated by Django 5.2.5 on 2025-09-04 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Tracker', '0007_alter_activityreport_options_alter_shift_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['shift_agent', 'shift_date'], 'verbose_name': 'Shift', 'verbose_name_plural': 'Shifts'},
        ),
    ]
