# Generated by Django 5.2.5 on 2025-09-07 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Tracker', '0002_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeProfile',
            new_name='Employee',
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['user__id'], 'permissions': (('can_create_report', 'create reports'), ('can_view_report', 'view reports'), ('can_update_report', 'update reports'), ('can_delete_report', 'delete reports'), ('can_add_users', 'add users'), ('can_modify_users', 'modify users')), 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
    ]
