# Generated by Django 5.2.5 on 2026-03-25 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_department_description_department_head_node_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.CharField(blank=True, default='Enterprise Support', max_length=100, null=True),
        ),
    ]
