# Generated by Django 5.2.5 on 2025-10-28 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_employee_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['user__id'], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
    ]
