# Generated by Django 5.2.5 on 2025-08-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_employee_employeeprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default='test@gmail.com', max_length=254, unique=True),
        ),
    ]
