# Generated by Django 5.2.5 on 2025-08-26 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveConstraint(
            model_name='customuser',
            name='unique_email',
        ),
        migrations.AlterModelTable(
            name='customuser',
            table=None,
        ),
    ]
