# Generated by Django 5.2.5 on 2025-12-28 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_employee_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user_type',
            field=models.CharField(choices=[('supervisor', 'Supervisor'), ('employee_agent', 'Employee Agent'), ('admin', 'Admin')], default='employee_agent', max_length=20),
        ),
    ]
