# Generated by Django 5.2.5 on 2026-06-22 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_employee_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='user_type',
            field=models.CharField(choices=[('supervisor', 'Supervisor'), ('employee_agent', 'Employee_Agent'), ('admin', 'Admin')], default='employee_agent', max_length=20),
        ),
    ]
