# Generated by Django 5.2.5 on 2025-08-26 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['email'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['title'], 'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='employeeprofile',
            options={'ordering': ['employee_id'], 'verbose_name': 'Employee Profile', 'verbose_name_plural': 'Employee Profiles'},
        ),
        migrations.AlterUniqueTogether(
            name='employeeprofile',
            unique_together={('employee_id', 'department')},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='accounts.CustomUser',
        ),
        migrations.AlterModelTable(
            name='department',
            table='Department',
        ),
    ]
