# Generated by Django 5.2.5 on 2025-08-26 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_options_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table=None,
        ),
        migrations.AlterModelTable(
            name='employeeprofile',
            table='employee_profile',
        ),
    ]
