# Generated by Django 5.2.5 on 2025-08-26 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_table_alter_employeeprofile_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeprofile',
            options={'verbose_name': 'Employee Profile', 'verbose_name_plural': 'Employee Profiles'},
        ),
        migrations.AlterUniqueTogether(
            name='employeeprofile',
            unique_together={('supervisor', 'department')},
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='employee_id',
        ),
    ]
