# Generated by Django 5.2.5 on 2025-08-26 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_employeeprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='employeeprofile',
            options={'ordering': ['user_id'], 'verbose_name': 'Employee Profile', 'verbose_name_plural': 'Employee Profiles'},
        ),
    ]
